name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Make installable package
      run: make

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: snowdog
        path: snowdog.tgz
